# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0009_auto_20170203_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
    ]
