# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0016_auto_20170203_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_staff_account', models.BooleanField(default=False)),
                ('has_filled_data', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('activation_key', models.CharField(max_length=40)),
                ('key_expires', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=7, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('dob', models.DateField(null=True, verbose_name='Date of Birth')),
                ('phone_number', models.CharField(max_length=10)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='student-uploaded-images', verbose_name='profile pic (1:1 square)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reminder.CustomUser')),
            ],
            options={
                'permissions': (('can_approve_student', 'Can approve student'), ('can_approve_staffs', 'Can approve staffs')),
            },
        ),
    ]
