# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0019_auto_20170210_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reminder.Author'),
        ),
    ]
