# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0020_auto_20170211_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_staff_account', models.BooleanField(default=False)),
                ('has_filled_data', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('activation_key', models.CharField(max_length=40)),
                ('key_expires', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=7, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('dob', models.DateField(null=True, verbose_name='Date of Birth')),
                ('phone_number', models.CharField(max_length=10)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='owner-uploaded-images', verbose_name='profile pic (1:1 square)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reminder.CustomUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.AddField(
            model_name='note',
            name='priority',
            field=models.CharField(choices=[('1', 'NO'), ('2', 'LOW'), ('3', 'MEDIUM'), ('4', 'HIGH')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reminder.Owner'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
