# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0021_auto_20170213_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff_account',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='list',
            name='note',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reminder.Note'),
        ),
    ]
