# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0024_auto_20170219_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminder.CustomUser'),
        ),
    ]
